#!/usr/bin/env python

Import('env')
Import('env_modules')

env_dr = env_modules.Clone()

env_dr.add_source_files(env.modules_sources, "*.cpp")
env_dr.add_source_files(env.modules_sources, "kann/*.c")
env_dr.add_source_files(env.modules_sources, "kann/kann_extra/*.c")
env_dr.MLP_KNOWLEDGE("data/mnist_mlp.knw")
env_dr.Append(CPPPATH=["kann"])

## Disable forcing a C++ standard, since newer Godot versions are built
## with -std=gnu++14. See https://github.com/godotengine/godot/issues/48479
# if not env.msvc:
#     env_dr.Append(CXXFLAGS=["-std=c++11"])
